## Transformers BERT:
Paper on BERT: https://jalammar.github.io/illustrated-bert/
Tutorial(Krish Nair): https://www.youtube.com/watch?v=DkzbCJtFvqM , https://www.youtube.com/watch?v=V1-Hm2rNkik&t=4s
The Artificial Guy : https://www.youtube.com/watch?v=wp9BudYGZyA
Emotion Detection using BERT(ABHISHEK JAISHWAL): https://www.youtube.com/watch?v=RgpANRh44ao


In [1]:
!pip install transformers==4.21.3

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.7 MB 15.3 MB/s 
     |████████████████████████████████| 6.6 MB 58.5 MB/s 
     |████████████████████████████████| 120 kB 72.4 MB/s 


In [ ]:
%%time
from transformers import pipeline
classifier = pipeline('sentiment-analysis',model="nlptown/bert-base-multilingual-uncased-sentiment")

CPU times: user 5.89 s, sys: 1.23 s, total: 7.12 s
Wall time: 8.92 s


In [ ]:
# from transformers import pipeline
# classifier = pipeline('sentiment-analysis',model= "philschmid/distilbert-base-multilingual-cased-sentiment-2")

In [ ]:
classifier('We are very happy to show you the 🤗 Transformers library.')

[{'label': '5 stars', 'score': 0.7725349068641663}]

In [ ]:
classifier("Attendence Bio-metric is big time consuming and hectic work.  Unhappy with the system. Requested to use Face Recognition.")

[{'label': '1 star', 'score': 0.4902504086494446}]

In [ ]:
result = classifier("Should improve Team Collaboration and Professional Gatherings with clients.")

In [ ]:
result[0]["label"][0]

'4'

In [ ]:
def func(text):
  result = classifier(text)
  label = result[0]["label"][0]
  dic = {'1': "More Negative","2":"Negative","3":"Neutral","4":"Postive","5": "More Positive"}
  label = dic[label]
  return label

Questionaire Part

In [2]:
import pandas as pd

In [3]:
manager_data= pd.read_excel("/content/drive/MyDrive/TALENT SPOTIFY/model_questions.xlsx",sheet_name='Manager')

manager_data.head()

QNO                                           Question Employer  \
0    1  What is the one thing you would like to change...  Manager   
1    2  What is the one thing you would like to change...  Manager   
2    3  What is the one thing you would like to contin...  Manager   
3    4  What is the one thing you would like to contin...  Manager   

                                            Response  
0  Team Verbal Communication is not satisfying sh...  
1  Attendence Bio-metric is big time consuming an...  
2  Flexible work hours. Enhancing their communica...  
3  Should improve Team Collaboration and Professi...

In [4]:
peer_data = pd.read_excel("/content/drive/MyDrive/TALENT SPOTIFY/model_questions.xlsx",sheet_name='Peers')

peer_data

QNO                                           Question Employer  \
0     1  What is the one thing you would like to change...   Peer 1   
1     1  What is the one thing you would like to change...   Peer 2   
2     1  What is the one thing you would like to change...   Peer 3   
3     2  What is the one thing you would like to change...   Peer 1   
4     2  What is the one thing you would like to change...   Peer 2   
5     2  What is the one thing you would like to change...   Peer 3   
6     3  What is the one thing you would like to contin...   Peer 1   
7     3  What is the one thing you would like to contin...   Peer 2   
8     3  What is the one thing you would like to contin...   Peer 3   
9     4  What is the one thing you would like to contin...   Peer 1   
10    4  What is the one thing you would like to contin...   Peer 2   
11    4  What is the one thing you would like to contin...   Peer 3   

                                             Response  
0   Take on a new skill. Motivation, team support ...  
1   Have thorough understanding of the complete pr...  
2                        Wish for better team leaders  
3   Have sufficient resource back up to fulfill th...  
4   Remove WFM (Work in everyone's happly in company)  
5   The employee training programs are rigorous. Y...  
6                              Problem Solving Skills  
7   I am interested in the ways this job can help ...  
8   Not sharing their knowledge and the lack of te...  
9          Motivation, team support and encouragement  
10             Flexible working hours, Value Employee  
11    Providing Good Benfits, Bonous to the employees

In [5]:
self_data = pd.read_excel("/content/drive/MyDrive/TALENT SPOTIFY/model_questions.xlsx",sheet_name='Self')
self_data

QNO                                           Question Employer  \
0    1  What is the one thing you would like to change...     Self   
1    2  What is the one thing you would like to change...     Self   
2    3  What is the one thing you would like to contin...     Self   
3    4  What is the one thing you would like to contin...     Self   

                                            Response  
0                             Boss to quit or retire  
1    As the work culture is unfair, need to improve.  
2                         Working within time limits  
3  Company should mould the employees by training...

In [ ]:
manager_data["Polarity"] = manager_data["Response"].apply(func)
peer_data["Polarity"] = peer_data["Response"].apply(func)
self_data["Polarity"] = self_data["Response"].apply(func)

In [ ]:
manager_data

QNO                                           Question Employer  \
0    1  What is the one thing you would like to change...  Manager   
1    2  What is the one thing you would like to change...  Manager   
2    3  What is the one thing you would like to contin...  Manager   
3    4  What is the one thing you would like to contin...  Manager   

                                            Response       Polarity  
0  Team Verbal Communication is not satisfying sh...       Negative  
1  Attendence Bio-metric is big time consuming an...  More Negative  
2  Flexible work hours. Enhancing their communica...        Postive  
3  Should improve Team Collaboration and Professi...        Postive

In [ ]:
peer_data

QNO                                           Question Employer  \
0     1  What is the one thing you would like to change...   Peer 1   
1     1  What is the one thing you would like to change...   Peer 2   
2     1  What is the one thing you would like to change...   Peer 3   
3     2  What is the one thing you would like to change...   Peer 1   
4     2  What is the one thing you would like to change...   Peer 2   
5     2  What is the one thing you would like to change...   Peer 3   
6     3  What is the one thing you would like to contin...   Peer 1   
7     3  What is the one thing you would like to contin...   Peer 2   
8     3  What is the one thing you would like to contin...   Peer 3   
9     4  What is the one thing you would like to contin...   Peer 1   
10    4  What is the one thing you would like to contin...   Peer 2   
11    4  What is the one thing you would like to contin...   Peer 3   

                                             Response       Polarity  
0   Take on a new skill. Motivation, team support ...  More Positive  
1   Have thorough understanding of the complete pr...        Postive  
2                        Wish for better team leaders        Neutral  
3   Have sufficient resource back up to fulfill th...        Postive  
4   Remove WFM (Work in everyone's happly in company)  More Positive  
5   The employee training programs are rigorous. Y...        Postive  
6                              Problem Solving Skills        Postive  
7   I am interested in the ways this job can help ...  More Positive  
8   Not sharing their knowledge and the lack of te...       Negative  
9          Motivation, team support and encouragement  More Positive  
10             Flexible working hours, Value Employee  More Positive  
11    Providing Good Benfits, Bonous to the employees        Postive

In [ ]:
self_data

QNO                                           Question Employer  \
0    1  What is the one thing you would like to change...     Self   
1    2  What is the one thing you would like to change...     Self   
2    3  What is the one thing you would like to contin...     Self   
3    4  What is the one thing you would like to contin...     Self   

                                            Response       Polarity  
0                             Boss to quit or retire  More Negative  
1    As the work culture is unfair, need to improve.       Negative  
2                         Working within time limits        Postive  
3  Company should mould the employees by training...        Postive

In [ ]:
from collections import Counter
import operator
main_list=[]
for i in range(1,5):
    # sub_list=[]
    peer_response = peer_data[peer_data["QNO"]== i]["Polarity"]
    response_list = list(peer_response)
    g= Counter(response_list)
    
    d=sorted(g.items(), key = operator.itemgetter(1), reverse=True)
    # print(f"{d} --> for question ({i})")
    question = tuple(manager_data[manager_data["QNO"]==i]["Question"])[0]
    mgr_response = tuple(manager_data[manager_data["QNO"]==i]["Polarity"])[0]
    peer_response = d[0][0]
    self_response = tuple(self_data[self_data["QNO"]==i]["Polarity"])[0]
    main_list.extend([[i,question,mgr_response,peer_response,self_response]])
    # main_list.extend(sub_list)
final_data = pd.DataFrame(data=main_list, columns=["QNo","Question","Manager","Peer","Self"])
final_data

QNo                                           Question        Manager  \
0    1  What is the one thing you would like to change...       Negative   
1    2  What is the one thing you would like to change...  More Negative   
2    3  What is the one thing you would like to contin...        Postive   
3    4  What is the one thing you would like to contin...        Postive   

            Peer           Self  
0  More Positive  More Negative  
1        Postive       Negative  
2        Postive        Postive  
3  More Positive        Postive

In [ ]:
def ranges(x):
  if x==0:
    return "Neutral"
  elif x>0 and x<= 1.5:
    return "Positive"
  elif x>1.5:
    return "More Postive"
  elif x<0 and x>=-1.5:
    return "Negative"
  else:
    return "More Negative"

In [ ]:
def overall_polarity(data):
  total=0
  
  dic = {"More Negative" : -2 , "Negative" : -1 ,"Neutral" : 0, "Postive" : 1 ,"More Positive" : 2}
  for i in ["Manager","Peer","Self"]:
    sum=0
    for j in data[i]:
      sum += dic[j]

    if i == "Manager":
      total += sum * 0.5
    
    elif i == "Peer":
      total += sum * 0.3
    
    else:
      total += sum * 0.2
    
  res = ranges(total)  
    
  return round(total,1), res

# ovl_polarity = overall_polarity(final_data)
print(f"The Overall Polarity: {overall_polarity(final_data)}")




The Overall Polarity: (1.1, 'Positive')


## ***DOWNLOADING A PRETRAINED MODEL AND UTILIZE IT IN PRODUCTION***

In [50]:
import pandas as pd
import tensorflow as tf
import numpy as np
from transformers import TFAutoModel,AutoTokenizer, TFAutoModelForSequenceClassification
from tqdm import tqdm

In [ ]:
#Read the data
manager_data= pd.read_excel("/content/drive/MyDrive/TALENT SPOTIFY/model_questions.xlsx",sheet_name='Manager')
peer_data = pd.read_excel("/content/drive/MyDrive/TALENT SPOTIFY/model_questions.xlsx",sheet_name='Peers')
self_data = pd.read_excel("/content/drive/MyDrive/TALENT SPOTIFY/model_questions.xlsx",sheet_name='Self')


In [7]:
%%time
from transformers import AutoModel, AutoTokenizer, TFBertForSequenceClassification
tokenizer = AutoTokenizer.from_pretrained("nlptown/bert-base-multilingual-uncased-sentiment")
multi_model = TFBertForSequenceClassification.from_pretrained("nlptown/bert-base-multilingual-uncased-sentiment",from_pt=True,num_labels=5)
multi_model.save_pretrained("/content/drive/MyDrive/TALENT SPOTIFY/Pretrained BERT/Model")

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

All the weights of TFBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


CPU times: user 17.9 s, sys: 3.61 s, total: 21.5 s
Wall time: 34.8 s


In [48]:
import tensorflow as tf
import numpy as np
from transformers import TFAutoModel,AutoTokenizer, TFAutoModelForSequenceClassification

In [17]:
bert= TFAutoModelForSequenceClassification.from_pretrained("/content/drive/MyDrive/TALENT SPOTIFY/Pretrained BERT/",num_labels=5)
bert

Some layers from the model checkpoint at /content/drive/MyDrive/TALENT SPOTIFY/Pretrained BERT/ were not used when initializing TFBertForSequenceClassification: ['dropout_37']
- This IS expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertForSequenceClassification were initialized from the model checkpoint at /content/drive/MyDrive/TALENT SPOTIFY/Pretrained BERT/.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [ ]:
corpus = ["This meeting is adorable and wonderful","You are looking so furious"]
encoding = tokenizer(corpus,padding=True,truncation=True,max_length=256,return_tensors= 'tf')
encoding

{'input_ids': <tf.Tensor: shape=(2, 9), dtype=int32, numpy=
array([[  101, 10372, 17829, 10127, 39098, 50105, 10110, 49108,   102],
       [  101, 10855, 10320, 25044, 10297, 83113,   102,     0,     0]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(2, 9), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 9), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 0]], dtype=int32)>}

In [ ]:
d=model(encoding)
d

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[ 0.0132768 ,  0.09704378, -0.32250714,  0.02226879, -0.0222209 ],
       [ 0.00608312,  0.06498328, -0.34042916,  0.07243793, -0.04929293]],
      dtype=float32)>, hidden_states=None, attentions=None)

In [ ]:
print(d[0])

tf.Tensor(
[[-2.3524466  -2.722272   -0.6465133   1.6118301   3.2830632 ]
 [ 1.0842215   0.4261458  -0.55015826 -0.89383227 -0.17141649]], shape=(2, 5), dtype=float32)


In [ ]:
import tensorflow as tf
tf_predictions = tf.nn.softmax(d[0], axis=-1)
tf_predictions

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0.00294047, 0.00203144, 0.01619179, 0.15491049, 0.82392585],
       [0.46813136, 0.24242036, 0.09131995, 0.06476045, 0.13336782]],
      dtype=float32)>

In [ ]:
import numpy as np
np.argmax(tf_predictions,axis=-1)

array([4, 0])

In [ ]:
#BUILDING A MODEL
def model_build(model,tokenizer,data,col):
  corpus = data[col].tolist()
  encoding = tokenizer(corpus,padding=True,truncation=True,max_length=256,return_tensors= 'tf')
  tf_outputs = model(encoding)
  tf_predictions = tf.nn.softmax(tf_outputs[0], axis=-1)
  labels=np.argmax(tf_predictions,axis=-1)
  return labels

In [58]:
from tqdm import tqdm
def change_labels(arr):
  l=[]
  dic = {0: "More Negative",1 :"Negative",2:"Neutral",3:"Postive",4: "More Positive"}
  for i in tqdm(arr):
    l.append(dic[i])
  return l

In [54]:
def final_data():
  
  for i,j in tqdm(zip(['manager_labels','peer_labels','self_labels'],[manager_data,peer_data,self_data])):
    i = model_build(multi_model,tokenizer,j,"Response")
    j["Polarity"] = change_labels(i)
  return

In [ ]:
final= final_data()

0it [00:00, ?it/s]
100%|██████████| 4/4 [00:00<00:00, 30120.68it/s]
1it [00:00,  3.65it/s]
100%|██████████| 12/12 [00:00<00:00, 96052.76it/s]
2it [00:00,  4.39it/s]
100%|██████████| 4/4 [00:00<00:00, 16448.25it/s]
3it [00:00,  4.46it/s]


In [ ]:
final

In [ ]:
from collections import Counter
import operator
main_list=[]
for i in range(1,5):
    # sub_list=[]
    peer_response = peer_data[peer_data["QNO"]== i]["Polarity"]
    response_list = list(peer_response)
    g= Counter(response_list)
    
    d=sorted(g.items(), key = operator.itemgetter(1), reverse=True)
    # print(f"{d} --> for question ({i})")
    question = tuple(manager_data[manager_data["QNO"]==i]["Question"])[0]
    mgr_response = tuple(manager_data[manager_data["QNO"]==i]["Polarity"])[0]
    peer_response = d[0][0]
    self_response = tuple(self_data[self_data["QNO"]==i]["Polarity"])[0]
    main_list.extend([[i,question,mgr_response,peer_response,self_response]])
    # main_list.extend(sub_list)
final_data = pd.DataFrame(data=main_list, columns=["QNo","Question","Manager","Peer","Self"])
final_data

QNo                                           Question        Manager  \
0    1  What is the one thing you would like to change...       Negative   
1    2  What is the one thing you would like to change...  More Negative   
2    3  What is the one thing you would like to contin...        Postive   
3    4  What is the one thing you would like to contin...        Postive   

            Peer           Self  
0  More Positive  More Negative  
1        Postive       Negative  
2        Postive        Postive  
3  More Positive        Postive

In [ ]:
def ranges(x):
  if x==0:
    return "Neutral"
  elif x>0 and x<= 1.5:
    return "Positive"
  elif x>1.5:
    return "More Postive"
  elif x<0 and x>=-1.5:
    return "Negative"
  else:
    return "More Negative"

In [ ]:
def overall_polarity(data):
  total=0
  
  dic = {"More Negative" : -2 , "Negative" : -1 ,"Neutral" : 0, "Postive" : 1 ,"More Positive" : 2}
  for i in ["Manager","Peer","Self"]:
    sum=0
    for j in data[i]:
      sum += dic[j]

    if i == "Manager":
      total += sum * 0.5
    
    elif i == "Peer":
      total += sum * 0.3
    
    else:
      total += sum * 0.2
    
  res = ranges(total)  
    
  return round(total,1), res

# ovl_polarity = overall_polarity(final_data)
print(f"The Overall Polarity: {overall_polarity(final_data)}")




The Overall Polarity: (1.1, 'Positive')


Saving the Model

In [47]:
multi_model.save_pretrained("/content/drive/MyDrive/TALENT SPOTIFY/Pretrained BERT/Model")
tokenizer.save_pretrained("/content/drive/MyDrive/TALENT SPOTIFY/Pretrained BERT/Model")

('/content/drive/MyDrive/TALENT SPOTIFY/Pretrained BERT/Model/tokenizer_config.json',
 '/content/drive/MyDrive/TALENT SPOTIFY/Pretrained BERT/Model/special_tokens_map.json',
 '/content/drive/MyDrive/TALENT SPOTIFY/Pretrained BERT/Model/vocab.txt',
 '/content/drive/MyDrive/TALENT SPOTIFY/Pretrained BERT/Model/added_tokens.json',
 '/content/drive/MyDrive/TALENT SPOTIFY/Pretrained BERT/Model/tokenizer.json')

In [ ]:
multi_model.summary()

Model: "tf_bert_for_sequence_classification"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bert (TFBertMainLayer)      multiple                  167356416 
                                                                 
 dropout_37 (Dropout)        multiple                  0         
                                                                 
 classifier (Dense)          multiple                  3845      
                                                                 
Total params: 167,360,261
Trainable params: 167,360,261
Non-trainable params: 0
_________________________________________________________________


LOADING THE TOKENIZER AND MODEL

lets verify with some other example

In [27]:
from transformers import TFAutoModel,AutoTokenizer, TFAutoModelForSequenceClassification
tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/TALENT SPOTIFY/Pretrained BERT")
# model = TFAutoModelForSequenceClassification.from_pretrained("/content/drive/MyDrive/TALENT SPOTIFY/Pretrained BERT/tf_model.h5",from_pt=True, num_labels=5)

In [28]:
d=tokenizer("I am happy")
d

{'input_ids': [101, 151, 10345, 19308, 102], 'token_type_ids': [0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1]}

To load the pretrained bert Model, tokenizer just import the followed libraries: AutoTokenizer, TFAutoModelForSequenceClassification.

Steps:
1. Specify the path of the model and tokenizer directory only not with its file names.
2. During Loading the model, when it is already saved in tensorflow weights no need to pass the flag("from_pt=True").

In [31]:
# from transformers import TFAutoModel,AutoTokenizer, TFAutoModelForSequenceClassification
# import tensorflow as tf
# # tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/TALENT SPOTIFY/Pretrained BERT/tokenizer.json")
# # model = tf.keras.models.load_model("/content/drive/MyDrive/TALENT SPOTIFY/Pretrained BERT/tf_model.h5")
model = TFAutoModelForSequenceClassification.from_pretrained("/content/drive/MyDrive/TALENT SPOTIFY/Pretrained BERT",num_labels=5)

Some layers from the model checkpoint at /content/drive/MyDrive/TALENT SPOTIFY/Pretrained BERT were not used when initializing TFBertForSequenceClassification: ['dropout_37']
- This IS expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertForSequenceClassification were initialized from the model checkpoint at /content/drive/MyDrive/TALENT SPOTIFY/Pretrained BERT.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


SHOULD NOT SUPPOSE TO LOAD LIBRARIES LIKE BELOW TWO CELLS 👇

In [ ]:
# from transformers import AutoConfig, TFAutoModel, TFBertForSequenceClassification,TFAutoModelForSequenceClassification
# config = AutoConfig.from_pretrained("/content/drive/MyDrive/TALENT SPOTIFY/Pretrained BERT/config.json",from_pt=True,num_labels=5)
# model = TFAutoModelForSequenceClassification.from_config(config)

In [ ]:
# model =TFBertForSequenceClassification.from_pretrained("/content/drive/MyDrive/TALENT SPOTIFY/Pretrained BERT/tf_model.h5")

☝️☝️☝️

In [59]:
corpus=["i am very bad boy","you are very beautiful", "You are looking furious"]
e=tokenizer(corpus,padding=True,truncation=True,max_length=256,return_tensors= 'tf')
results=model(e)
tf_predictions = tf.nn.softmax(results[0], axis=-1)
labels=np.argmax(tf_predictions,axis=-1)
print(labels)
labels =change_labels(labels)
labels

[0 4 0]


100%|██████████| 3/3 [00:00<00:00, 27900.03it/s]


['More Negative', 'More Positive', 'More Negative']

## Function to pass the entire data

In [38]:
 #BUILDING A MODEL
def model_build(model,tokenizer,data,col):
  corpus = data[col].tolist()
  encoding = tokenizer(corpus,padding=True,truncation=True,max_length=256,return_tensors= 'tf')
  tf_outputs = model(encoding)
  tf_predictions = tf.nn.softmax(tf_outputs[0], axis=-1)
  labels=np.argmax(tf_predictions,axis=-1)
  return labels

In [62]:
manager_labels = model_build(bert,tokenizer,self_data,"Response")
print(manager_labels)
manager_labels = change_labels(manager_labels)
print()
print(manager_labels)

[0 1 3 3]


100%|██████████| 4/4 [00:00<00:00, 30840.47it/s]


['More Negative', 'Negative', 'Postive', 'Postive']


# **THE END**